services:
  db:
    image: postgres
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: homeuserpass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
