# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: List NuGet Sources
      run: dotnet nuget list source
    - name: Clear Cache
      run: dotnet nuget locals all --clear
    - name: Restore NuGet packages
      run: dotnet restore
      env:
        DOTNET_RESTORE_SOURCE: https://nuget.pkg.github.com/kseretis/index.json
        GITHUB_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
